"""Autogenerated module docstring for access/ui/windows/log_viewer_window.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:24.216258Z
"""


from ui.windows.window_with_sidebar import WindowWithSidebar
from ui.pages.log_viewer_page import LogViewerPage   # or whatever your page is called

class LogViewerWindow(WindowWithSidebar):
    def __init__(self, user):
        self.current_user = user      # <-- REQUIRED
        super().__init__("Log Viewer")

    def _setup_pages(self):
        # The log viewer is typically an admin-only feature because log files
        # may contain sensitive diagnostics and exception details.
        self.add_page("Viewer", LogViewerPage)
