"""Autogenerated module docstring for access/ui/windows/sales_order_window.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:24.215258Z
"""


# ui/windows/sales_order_window.py

from ui.windows.window_with_sidebar import WindowWithSidebar
from ui.components.logger_utils import log_event

class SalesOrderWindow(WindowWithSidebar):
    def __init__(self, user, mongo, parent=None):
        super().__init__("Sales Orders", parent)

        self.user = user
        self.mongo = mongo
        self.current_user = user   # IMPORTANT: WindowWithSidebar expects this
        self.app = parent

        log_event("info", "SalesOrderWindow initialized", user=user.username)

        # Audit the opening of the sales orders module. This is a useful
        # operational event for security and usage tracking.
        try:
            self.mongo.log_event(
                event="sales_orders.window.open",
                performed_by=self.user.username,
                details="Opened Sales Orders module"
            )
        except Exception as e:
            log_event("error", "Failed to write audit log", error=str(e))

        self._setup_pages()

    def _setup_pages(self):
        # Add the Sales Orders List page
        self.add_page(
            "Sales Orders List",
            lambda: self._open_sales_orders_list(),
            required_permission="sales.read"
        )

    def _open_sales_orders_list(self):
        log_event("info", "Opening Sales Orders List Page", user=self.user.username)

        from ui.pages.sales.sales_order_list_page import SalesOrderListPage
        return SalesOrderListPage(self.user, self.mongo, parent=self)

    def show_error(self, message):
        from PySide6.QtWidgets import QMessageBox
        QMessageBox.critical(self, "Error", message)

    def show_info(self, message):
        from PySide6.QtWidgets import QMessageBox
        QMessageBox.information(self, "Info", message)