"""Autogenerated module docstring for access/ui/widgets/assembly_search_widget.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:24.177706Z
"""


from PySide6.QtWidgets import QWidget, QVBoxLayout, QLineEdit, QListWidget, QListWidgetItem
from PySide6.QtCore import Signal, Qt

class AssemblySearchWidget(QWidget):
    selected_item_changed = Signal(dict)

    def __init__(self, items_list: list[dict], parent=None):
        super().__init__(parent)

        self.items_list = items_list

        self.search_le = QLineEdit()
        self.search_le.setPlaceholderText("Search inventory...")
        self.search_le.textChanged.connect(self._filter_results)

        self.results_list = QListWidget()
        self.results_list.itemClicked.connect(self._on_item_selected)

        layout = QVBoxLayout()
        layout.addWidget(self.search_le)
        layout.addWidget(self.results_list)
        self.setLayout(layout)

        self._populate_all()

    # NOTE: This widget stores full item dicts on list items for convenience.
    # Be careful: the stored dicts may contain DB-only fields (e.g. password
    # hashes on user documents if reused accidentally). Callers should treat
    # the emitted dict as read-only and copy any values needed for mutation.

    def _populate_all(self):
        self.results_list.clear()
        for item in self.items_list:
            label = f"{item['part_number']} (Rev {item['revision']}) a {item.get('description','')}"
            lw_item = QListWidgetItem(label)
            lw_item.setData(Qt.UserRole, item)
            self.results_list.addItem(lw_item)

    def _filter_results(self, text):
        text = text.lower().strip()
        self.results_list.clear()

        for item in self.items_list:
            label = f"{item['part_number']} (Rev {item['revision']}) a {item.get('description','')}"
            if text in label.lower():
                lw_item = QListWidgetItem(label)
                lw_item.setData(Qt.UserRole, item)
                self.results_list.addItem(lw_item)

    def _on_item_selected(self, lw_item):
        item = lw_item.data(Qt.UserRole)
        self.selected_item_changed.emit(item)