"""Autogenerated module docstring for access\ui\widgets\bom_editor_widget.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:24.202852Z
"""


from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QComboBox,
    QPushButton, QScrollArea, QFrame, QSizePolicy
)
from PySide6.QtCore import Signal
from ui.widgets.bom_line_row import BOMLineRow


class BOMEditorWidget(QWidget):
    save_requested = Signal(dict)
    dirty_changed = Signal(bool)     # NEW — page listens to this

    def __init__(self, items_list: list[dict], parent=None):
        super().__init__(parent)

        self.items_list = items_list

        self.next_revision = None
        self.loaded_revision = None

        self.is_dirty = False              # Tracks whether the current BOM has unsaved changes
        self.block_dirty_signals = False   # Prevents change signals during programmatic loads

        # ---------------------------------------------------------
        # Assembly selector
        # ---------------------------------------------------------
        # Select the assembly part that this BOM belongs to.
        self.assembly_cb = QComboBox()
        for item in items_list:
            label = f"{item['part_number']} (Rev {item['revision']})"
            self.assembly_cb.addItem(label)
            index = self.assembly_cb.count() - 1
            self.assembly_cb.setItemData(index, item)

        # User changing assembly = dirty
        self.assembly_cb.currentIndexChanged.connect(
            lambda: self._set_dirty(True)
        )

        # ---------------------------------------------------------
        # Revision selector
        # ---------------------------------------------------------
        # Pick the revision for the BOM being saved.
        self.revision_cb = QComboBox()
        self.revision_cb.addItems(["A", "B", "C"])

        # ---------------------------------------------------------
        # Buttons
        # ---------------------------------------------------------
        # UI actions for adding a component row or saving the current BOM.

        self.add_btn = QPushButton("Add Component")
        self.add_btn.clicked.connect(self._add_line)

        self.save_btn = QPushButton("Save BOM")
        self.save_btn.clicked.connect(self._save_bom)

        # ---------------------------------------------------------
        # Component rows container
        # ---------------------------------------------------------
        # The BOM row widgets are stacked vertically inside this container.
        self.lines_container = QWidget()
        self.lines_container.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)

        self.lines_layout = QVBoxLayout()
        self.lines_layout.setSpacing(0)
        self.lines_layout.setContentsMargins(0, 0, 0, 0)
        self.lines_container.setLayout(self.lines_layout)

        # ---------------------------------------------------------
        # Scroll area
        # ---------------------------------------------------------
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(self.lines_container)

        # ---------------------------------------------------------
        # Top controls
        # ---------------------------------------------------------
        top_layout = QHBoxLayout()
        top_layout.setContentsMargins(0, 0, 0, 0)
        top_layout.setSpacing(8)

        controls_layout = QHBoxLayout()
        controls_layout.setContentsMargins(0, 0, 0, 0)
        controls_layout.setSpacing(24)

        part_layout = QHBoxLayout()
        part_layout.setContentsMargins(0, 0, 0, 0)
        part_layout.setSpacing(2)
        part_layout.addWidget(QLabel("Part Number:"))
        part_layout.addWidget(self.assembly_cb)
        controls_layout.addLayout(part_layout)

        revision_layout = QHBoxLayout()
        revision_layout.setContentsMargins(0, 0, 0, 0)
        revision_layout.setSpacing(2)
        revision_layout.addWidget(QLabel("Revision:"))
        revision_layout.addWidget(self.revision_cb)
        controls_layout.addLayout(revision_layout)

        top_layout.addLayout(controls_layout)
        top_layout.addStretch(1)
        top_layout.addWidget(self.add_btn)
        top_layout.addWidget(self.save_btn)

        # ---------------------------------------------------------
        # Main layout
        # ---------------------------------------------------------
        main_layout = QVBoxLayout()
        main_layout.addLayout(top_layout)
        main_layout.addWidget(scroll)
        main_layout.setSpacing(6)
        main_layout.setContentsMargins(6, 6, 6, 6)
        

        self.setLayout(main_layout)

    # ---------------------------------------------------------
    # Dirty flag handling
    # ---------------------------------------------------------
    def _set_dirty(self, value: bool):
        """Mark the editor dirty and emit the state change."""
        if self.block_dirty_signals:
            return

        self.is_dirty = value
        self.dirty_changed.emit(value)


    def _clear_dirty(self):
        """Clear the dirty flag without emitting an extra save event."""
        self._set_dirty(False)

    # ---------------------------------------------------------
    # Add a new row (user action)
    # ---------------------------------------------------------
    def _add_line(self):
        """Create and append a new BOM component row for the user."""
        row = BOMLineRow(self.items_list)
        row.remove_requested.connect(self._remove_line)
        row.changed.connect(lambda: self._set_dirty(True))   # NEW

        frame = QFrame()
        frame.setFrameShape(QFrame.NoFrame)
        frame_layout = QVBoxLayout(frame)
        frame_layout.setSpacing(0)
        frame_layout.setContentsMargins(0, 0, 0, 0)
        frame_layout.addWidget(row)

        self.lines_layout.addWidget(frame)
        self._set_dirty(True)

        # NOTE: When rows are added programmatically during a BOM load the
        # parent page sets `block_dirty_signals=True` so the `row.changed`
        # handler will return early and not mark the editor dirty. User-initiated
        # additions (this method) intentionally mark the editor dirty so the
        # caller can prompt to save.

    # ---------------------------------------------------------
    # Remove row
    # ---------------------------------------------------------
    def _remove_line(self, row_widget):
        """Remove the selected row from the BOM and mark the editor dirty."""
        row_widget.setParent(None)
        row_widget.deleteLater()
        self._set_dirty(True)

    # ---------------------------------------------------------
    # Save BOM
    # ---------------------------------------------------------
    def _save_bom(self):
        """Collect BOM data from the UI and emit it for persistence."""
        assembly_item = self.assembly_cb.currentData()

        data = {
            "assembly_part_number": assembly_item["part_number"],
            "assembly_revision": assembly_item["revision"],
            "revision": self.next_revision or self.revision_cb.currentText(),
            "lines": []
        }

        for i in range(self.lines_layout.count()):
            frame = self.lines_layout.itemAt(i).widget()
            row = frame.findChild(BOMLineRow)
            if row:
                row_data = row.get_data()
                if row_data:
                    data["lines"].append(row_data)

        self.save_requested.emit(data)
        self.next_revision = None
        self._clear_dirty()

    # ---------------------------------------------------------
    # Clear all rows
    # ---------------------------------------------------------
    def clear_rows(self):
        """Remove every existing BOM component row from the editor."""
        while self.lines_layout.count() > 0:
            item = self.lines_layout.takeAt(0)
            widget = item.widget()
            if widget:
                widget.setParent(None)
                widget.deleteLater()

    # ---------------------------------------------------------
    # Add row from DB (auto-load)
    # ---------------------------------------------------------
    def add_row(self, component_part_number, component_revision, quantity, uom, comments, quantity_type):
        """Add one BOM component line pre-populated from stored data."""
        row = BOMLineRow(self.items_list)

        label = f"{component_part_number} (Rev {component_revision})"
        row.item_le.setText(label)

        row.qty_sb.setValue(float(quantity))
        row.comments_le.setText(comments)
        row.qty_type_cb.setCurrentText(quantity_type)

        row.remove_requested.connect(self._remove_line)
        row.changed.connect(lambda: self._set_dirty(True))   # NEW

        frame = QFrame()
        frame.setFrameShape(QFrame.NoFrame)
        frame_layout = QVBoxLayout(frame)
        frame_layout.setSpacing(0)
        frame_layout.setContentsMargins(0, 0, 0, 0)
        frame_layout.addWidget(row)

        self.lines_layout.addWidget(frame)
        # When invoked during load the parent typically sets
        # `self.block_dirty_signals=True` to avoid triggering the dirty
        # indicator from these programmatic updates. The `row.changed`
        # connection remains the same so interactive edits still work.