"""Autogenerated module docstring for access\ui\pages\admin\dialogs\edit_store_location_dialog.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:23.958340Z
"""


# ui/pages/admin/dialogs/edit_store_location_dialog.py

from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QLabel,
    QLineEdit, QPushButton, QMessageBox
)
from ui.components.logger_utils import log_event


class EditStoreLocationDialog(QDialog):
    def __init__(self, mongo, user, location, parent=None):
        super().__init__(parent)
        self.mongo = mongo
        self.user = user
        self.location = location

        self.setWindowTitle(f"Edit Location — {location['location_name']}")
        self.setMinimumWidth(350)

        layout = QVBoxLayout(self)

        # Name
        layout.addWidget(QLabel("Location Name"))
        self.name = QLineEdit(location.get("location_name", ""))
        layout.addWidget(self.name)

        # Description
        layout.addWidget(QLabel("Description"))
        self.description = QLineEdit(location.get("description", ""))
        layout.addWidget(self.description)

        # Buttons
        btn_row = QHBoxLayout()
        btn_save = QPushButton("Save")
        btn_cancel = QPushButton("Cancel")

        btn_save.clicked.connect(self.save)
        btn_cancel.clicked.connect(self.reject)

        btn_row.addWidget(btn_save)
        btn_row.addWidget(btn_cancel)
        layout.addLayout(btn_row)

    def save(self):
        name = self.name.text().strip()

        if not name:
            QMessageBox.warning(self, "Missing Field", "Location name is required.")
            return

        self.mongo.store_locations.update_one(
            {"_id": self.location["_id"]},
            {
                "$set": {
                    "location_name": name,
                    "description": self.description.text().strip()
                }
            }
        )

        self.mongo.audit(
            "store_location.update",
            self.user.username,
            target=name,
            details={"previous_name": self.location.get("location_name"), "description": self.description.text().strip()}
        )
        log_event("info", "Store location updated", user=self.user.username, target=name)

        self.accept()