"""Autogenerated module docstring for access/models/user.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:23.073435Z
"""


class User:
    def __init__(self, username, role, permissions):
        self.username = username
        self.role = role
        self.permissions = permissions or []

    def has_permission(self, permission: str) -> bool:
        return permission in self.permissions