"""Autogenerated module docstring for access/services/mongo_service.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:23.103696Z
"""


from dataclasses import fields

from pymongo import MongoClient
from bson.objectid import ObjectId
from ui.components.logger import logger
from ui.components.logger_utils import log_event
from datetime import datetime
import bcrypt
import re


_SENSITIVE_AUDIT_KEYS = {
    "password",
    "password_hash",
    "token",
    "access_token",
    "refresh_token",
    "secret",
    "api_key",
    "credentials",
}


def _sanitize_audit_value(value, key=None):
    """Redact sensitive fields recursively before writing audits.

    - If a key looks sensitive (password, token, secret etc.) the value
      is replaced with the string "[REDACTED]".
    - Works recursively for dict/list/tuple structures so nested secrets
      won't be accidentally stored in the audit log.
    """
    # Shortcut: if this value is keyed by a sensitive name, redact it.
    if key and key.lower() in _SENSITIVE_AUDIT_KEYS:
        return "[REDACTED]"

    # Recurse into dicts and sequence types to sanitize nested values.
    if isinstance(value, dict):
        return {name: _sanitize_audit_value(item, name) for name, item in value.items()}
    if isinstance(value, (list, tuple)):
        return type(value)(_sanitize_audit_value(item) for item in value)
    return value


class MongoService:

    """class MongoService - TODO: add description.
    Generated: 2026-08-01T21:49:18.295802Z
    """
    EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

    DEFAULT_ROLE_PERMISSIONS = {
        "viewer": ["basic.view"],
        "user": ["basic.view", "basic.edit"],
        "manager": ["basic.view", "basic.edit", "users.read", "users.write"],
        "admin": ["*"]
    }

    def __init__(self, uri="mongodb://localhost:27017", db_name="test"):
        """function __init__ - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        try:
            self.client = MongoClient(uri)
            self.db = self.client[db_name]

            # Collections
            self.users = self.db["users"]
            self.roles = self.db["roles"]
            self.permissions = self.db["permissions"]
            self.inventory = self.db["inventory"]
            self.logs = self.db["logs"]
            self.audit_log = self.db["audit_log"]
            self.inventory_batches = self.db["inventory_batches"]
            self.stock_movements = self.db["stock_movements"]

            self.stores = self.db["stores"]
            self.uom_list = self.db["uom_list"]
            self.suppliers = self.db["suppliers"]
            self.store_locations = self.db["store_locations"]

            self.bom = self.db["bom"]
            self.sales_orders = self.db["sales_orders"]
            self.works_orders = self.db["works_orders"]
            self.shop_orders = self.db["shop_orders"]
            self.purchase_orders = self.db["purchase_orders"]
            self.inventory_movements = self.db["inventory_movements"]



            # ⭐ OPTIONAL INDEX (recommended)
            self.store_locations.create_index("location_name", unique=True)
            self.stock_movements.create_index("movement_date")

            self.counters = self.db["counters"]
            self.sales_orders = self.db["sales_orders"]


            logger.info("Connected to MongoDB")
        except Exception as e:
            logger.error(f"MongoDB connection failed: {e}")
            raise


    # -------------------------------------------------
    # Helpers
    # -------------------------------------------------
    def validate_email_format(self, email: str) -> bool:
        """function validate_email_format - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        return bool(self.EMAIL_REGEX.match(email))

    def email_exists(self, email: str, exclude_user_id=None) -> bool:
        """function email_exists - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        query = {"email": email}
        if exclude_user_id:
            query["_id"] = {"$ne": ObjectId(exclude_user_id)}
        return self.users.find_one(query) is not None

    def username_exists(self, username: str, exclude_user_id=None) -> bool:
        """function username_exists - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        query = {"username": username}
        if exclude_user_id:
            query["_id"] = {"$ne": ObjectId(exclude_user_id)}
        return self.users.find_one(query) is not None

    def hash_password(self, password: str) -> str:
        """function hash_password - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
    
    def build_user_document(self, username, email, password, role="viewer", status="Active"):
        """function build_user_document - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        return {
            "username": username,
            "email": email,
            "password_hash": self.hash_password(password),
            "role": role,
            "permissions": self.DEFAULT_ROLE_PERMISSIONS.get(role, []),
            "status": status,
            "created_at": datetime.utcnow(),
            "last_login": None,
            "theme": "light"
        }


    # -------------------------------------------------
    # Authentication
    # -------------------------------------------------
    def authenticate(self, username, password):
        """function authenticate - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        try:
            user = self.users.find_one({"username": username})
            if not user:
                logger.info(f"Login failed: user '{username}' not found")
                return None

            stored_hash = user.get("password_hash")
            if not stored_hash:
                logger.error(f"User '{username}' has no password_hash field")
                return None

            # Use bcrypt's secure comparison to verify the password hash.
            if bcrypt.checkpw(password.encode(), stored_hash.encode()):
                logger.info(f"User '{username}' authenticated successfully")
                return user

            logger.info(f"Login failed: incorrect password for '{username}'")
            return None

        except Exception as e:
            logger.error(f"Authentication error: {e}")
            return None

    # -------------------------------------------------
    # Create user
    # -------------------------------------------------
    def create_user(self, user_doc, performed_by):
        # Email validation
        """function create_user - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        if not self.validate_email_format(user_doc["email"]):
            raise RuntimeError("Invalid email format.")

        if self.email_exists(user_doc["email"]):
            raise RuntimeError("Email already in use.")

        # Ensure role exists
        role = user_doc.setdefault("role", "viewer")

        # Assign default permissions
        default_perms = self.DEFAULT_ROLE_PERMISSIONS.get(role, [])
        user_doc.setdefault("permissions", default_perms.copy())

        try:
            # Persist the user first; only then emit audit/log events so logs
            # reflect completed state (avoid logging partially-failed operations).
            self.users.insert_one(user_doc)

            self.audit(
                event="user.create",
                performed_by=performed_by,
                target=user_doc.get("username"),
                details={
                    "email": user_doc.get("email"),
                    "role": user_doc.get("role"),
                    "permissions": user_doc.get("permissions"),
                }
            )

            log_event(
                "info",
                "User created",
                by=performed_by,
                target=user_doc.get("username"),
                role=role,
                permissions=",".join(user_doc.get("permissions", []))
            )

        except Exception as e:
            # Log the failure (no sensitive details included) and propagate.
            log_event(
                "error",
                "User creation failed",
                by=performed_by,
                target=user_doc.get("username"),
                error=str(e)
            )
            raise RuntimeError(f"Failed to create user: {e}")

    # -------------------------------------------------
    # Update user (admin)
    # -------------------------------------------------
    def update_user(self, user_id, update_doc, performed_by):

        # Email validation
        """function update_user - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        if "email" in update_doc:
            if not self.validate_email_format(update_doc["email"]):
                raise RuntimeError("Invalid email format.")

            if self.email_exists(update_doc["email"], exclude_user_id=user_id):
                raise RuntimeError("Email already in use.")

        try:
            self.users.update_one(
                {"_id": ObjectId(user_id)},
                {"$set": update_doc}
            )

            changed_fields = ", ".join(update_doc.keys())

            user = self.users.find_one({"_id": ObjectId(user_id)})
            username = user.get("username") if user else user_id

            log_event(
                "info",
                "User updated",
                by=performed_by,
                target=username,
                fields=changed_fields
            )
            self.audit(
                event="user.update",
                performed_by=performed_by,
                target=username,
                details=update_doc
            )


        except Exception as e:
            log_event(
                "error",
                "User update failed",
                by=performed_by,
                target=user_id,
                error=str(e)
            )
            raise RuntimeError(f"Failed to update user: {e}")
        
    def update_user_permissions(self, user_id, permissions, performed_by):
        """function update_user_permissions - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        self.users.update_one(
            {"_id": ObjectId(user_id)},
            {"$set": {"permissions": permissions}}
        )
        logger.info(f"Updated permissions for user {user_id} by {performed_by}")



    

    # -------------------------------------------------
    # Delete user (admin)
    # -------------------------------------------------
    def delete_user(self, user_id, performed_by):
        """function delete_user - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        try:
            user = self.users.find_one({"_id": ObjectId(user_id)})
            username = user.get("username") if user else user_id

            self.users.delete_one({"_id": ObjectId(user_id)})

            log_event(
                "warn",
                "User deleted",
                by=performed_by,
                target=username
            )
            self.audit(
                event="user.delete",
                performed_by=performed_by,
                target=username,
                details="User deleted"
            )


        except Exception as e:
            log_event(
                "error",
                "User deletion failed",
                by=performed_by,
                target=user_id,
                error=str(e)
            )
            raise RuntimeError(f"Failed to delete user: {e}")

    # -------------------------------------------------
    # Update permissions (admin)
    # -------------------------------------------------
    def update_permissions(self, user_id, new_permissions, performed_by):
        """function update_permissions - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        try:
            user = self.users.find_one({"_id": ObjectId(user_id)})
            username = user.get("username") if user else user_id

            old = set(user.get("permissions", []))
            new = set(new_permissions)

            added = new - old
            removed = old - new

            self.users.update_one(
                {"_id": ObjectId(user_id)},
                {"$set": {"permissions": list(new)}}
            )

            log_event(
                "info",
                "Permissions updated",
                by=performed_by,
                target=username,
                added=",".join(added),
                removed=",".join(removed)
            )
            self.audit(
                event="user.update_permissions",
                performed_by=performed_by,
                target=username,
                details={
                    "added": list(added),
                    "removed": list(removed)
                }
            )


        except Exception as e:
            log_event(
                "error",
                "Permission update failed",
                by=performed_by,
                target=user_id,
                error=str(e)
            )
            raise RuntimeError(f"Failed to update permissions: {e}")

    # -------------------------------------------------
    # Update role (admin)
    # -------------------------------------------------
    def update_role(self, user_id, new_role, performed_by):
        """function update_role - TODO: add description.
        Generated: 2026-08-01T21:49:18.295802Z
        """
        try:
            user = self.users.find_one({"_id": ObjectId(user_id)})
            username = user.get("username") if user else user_id

            new_permissions = self.DEFAULT_ROLE_PERMISSIONS.get(new_role, [])

            self.users.update_one(
                {"_id": ObjectId(user_id)},
                {"$set": {
                    "role": new_role,
                    "permissions": new_permissions
                }}
            )

            log_event(
                "info",
                "Role updated",
                by=performed_by,
                target=username,
                role=new_role,
                permissions=",".join(new_permissions)
            )
            self.audit(
                event="user.update_role",
                performed_by=performed_by,
                target=username,
                details={
                    "new_role": new_role,
                    "permissions": new_permissions
                }
            )


        except Exception as e:
            log_event(
                "error",
                "Role update failed",
                by=performed_by,
                target=user_id,
                error=str(e)
            )
            raise RuntimeError(f"Failed to update role: {e}")

    # -------------------------------------------------
    # Admin password reset
    # -------------------------------------------------
    def reset_password(self, user_id, new_password, performed_by):
        """function reset_password - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        try:
            user = self.users.find_one({"_id": ObjectId(user_id)})
            username = user.get("username") if user else user_id

            new_hash = self.hash_password(new_password)

            self.users.update_one(
                {"_id": ObjectId(user_id)},
                {"$set": {"password_hash": new_hash}}
            )

            log_event(
                "warn",
                "Password reset",
                by=performed_by,
                target=username
            )
            self.audit(
                event="user.reset_password",
                performed_by=performed_by,
                target=username,
                details="Password reset"
            )


        except Exception as e:
            log_event(
                "error",
                "Password reset failed",
                by=performed_by,
                target=user_id,
                error=str(e)
            )
            raise RuntimeError(f"Failed to reset password: {e}")

    # -------------------------------------------------
    # User self-service: update profile
    # -------------------------------------------------
    def update_profile(self, user_id, fields, performed_by):
        # print("TYPE OF user_id:", type(user_id), user_id)

        """function update_profile - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        fields.pop("_id", None)

        if "email" in fields:
            if not self.validate_email_format(fields["email"]):
                raise RuntimeError("Invalid email format.")

            if self.email_exists(fields["email"], exclude_user_id=user_id):
                raise RuntimeError("Email already in use.")

        try:
            self.users.update_one(
                {"_id": ObjectId(user_id)},
                {"$set": fields}
            )

            changed = ", ".join(fields.keys())

            log_event(
                "info",
                "Profile updated",
                by=performed_by,
                target=performed_by,
                fields=changed
            )

        except Exception as e:
            log_event(
                "error",
                "Profile update failed",
                by=performed_by,
                target=performed_by,
                error=str(e)
            )
            raise

    # -------------------------------------------------
    # User self-service: change password
    # -------------------------------------------------
    def change_password(self, user_id, old_pw, new_pw, performed_by):
        """function change_password - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        try:
            user = self.users.find_one({"_id": ObjectId(user_id)})
            if not user:
                raise RuntimeError("User not found.")

            stored_hash = user.get("password_hash")
            # Verify the supplied current password against the stored hash
            # before allowing a password change.
            if not bcrypt.checkpw(old_pw.encode(), stored_hash.encode()):
                raise RuntimeError("Current password is incorrect.")

            new_hash = self.hash_password(new_pw)

            self.users.update_one(
                {"_id": ObjectId(user_id)},
                {"$set": {"password_hash": new_hash}}
            )

            log_event(
                "info",
                "Password changed",
                by=performed_by,
                target=performed_by
            )

        except Exception as e:
            log_event(
                "error",
                "Password change failed",
                by=performed_by,
                target=performed_by,
                error=str(e)
            )
            raise

    def get_all_roles(self):
        """function get_all_roles - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        return list(self.db["roles"].find({}, {"_id": 0}))

    def get_role(self, name):
        """function get_role - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        return self.db["roles"].find_one({"name": name})
        
    def create_role(self, name, permissions, description, performed_by):
        """function create_role - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        if self.get_role(name):
            raise RuntimeError("Role already exists.")

        role_doc = {
            "name": name,
            "permissions": permissions,
            "description": description
        }

        self.db["roles"].insert_one(role_doc)

        self.audit(
            "role.create",
            performed_by,
            target=name,
            details={"permissions": list(permissions), "description": description}
        )

        log_event(
            "info",
            "Role created",
            by=performed_by,
            target=name,
            permissions=",".join(permissions)
        )

    def update_role(self, name, permissions, description, performed_by):
        """function update_role - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        if not self.get_role(name):
            raise RuntimeError("Role does not exist.")

        self.db["roles"].update_one(
            {"name": name},
            {"$set": {
                "permissions": permissions,
                "description": description
            }}
        )

        self.audit(
            "role.update",
            performed_by,
            target=name,
            details={"permissions": list(permissions), "description": description}
        )

        log_event(
            "info",
            "Role updated",
            by=performed_by,
            target=name,
            permissions=",".join(permissions)
        )

    def count_users_with_role(self, name):
        """function count_users_with_role - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        return self.users.count_documents({"role": name})

    def delete_role(self, name, performed_by):
        """function delete_role - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        count = self.count_users_with_role(name)
        if count > 0:
            raise RuntimeError(f"Cannot delete role '{name}' because {count} users have it.")

        self.db["roles"].delete_one({"name": name})

        self.audit("role.delete", performed_by, target=name)

        log_event(
            "warn",
            "Role deleted",
            by=performed_by,
            target=name
        )
    
    # -----------------------------
    # PERMISSIONS COLLECTION
    # -----------------------------

    def get_all_permissions(self):
        """function get_all_permissions - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        return list(self.permissions.find({}, {"_id": 0, "name": 1, "category": 1, "description": 1}))



    def get_permission(self, name):
        """function get_permission - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        return self.db["permissions"].find_one({"name": name})


    def create_permission(self, name, category, description, performed_by):
        """function create_permission - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        if self.get_permission(name):
            raise RuntimeError(f"Permission '{name}' already exists.")

        doc = {
            "name": name,
            "category": category,
            "description": description
        }

        self.db["permissions"].insert_one(doc)

        self.audit(
            "permission.create",
            performed_by,
            target=name,
            details={"category": category, "description": description}
        )

        log_event(
            "info",
            "Permission created",
            by=performed_by,
            target=name
        )


    def update_permission(self, name, category, description, performed_by):
        """function update_permission - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        if not self.get_permission(name):
            raise RuntimeError(f"Permission '{name}' does not exist.")

        self.db["permissions"].update_one(
            {"name": name},
            {"$set": {
                "category": category,
                "description": description
            }}
        )

        self.audit(
            "permission.update",
            performed_by,
            target=name,
            details={"category": category, "description": description}
        )

        log_event(
            "info",
            "Permission updated",
            by=performed_by,
            target=name
        )


    def delete_permission(self, name, performed_by):
        # Safety check: ensure no roles use this permission
        """function delete_permission - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        count = self.count_roles_using_permission(name)
        if count > 0:
            raise RuntimeError(f"Cannot delete permission '{name}' because {count} roles use it.")

        self.db["permissions"].delete_one({"name": name})

        self.audit("permission.delete", performed_by, target=name)

        log_event(
            "warn",
            "Permission deleted",
            by=performed_by,
            target=name
        )

    def count_users_using_permission(self, permission_name):
        """function count_users_using_permission - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        return self.users.count_documents({"permissions": permission_name})

    def count_roles_using_permission(self, permission_name):
        """function count_roles_using_permission - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        return self.roles.count_documents({"permissions": permission_name})

    def count_total_usage_of_permission(self, permission_name):
        """function count_total_usage_of_permission - TODO: add description.
        Generated: 2026-08-01T21:49:18.297307Z
        """
        users = self.count_users_using_permission(permission_name)
        roles = self.count_roles_using_permission(permission_name)
        return users + roles

    def audit(self, event, performed_by, target=None, details=None):
        """Write a sanitized audit document to the `audit_log` collection.

        We sanitize `target` and `details` to avoid persisting secrets, and
        always include a timestamp so entries can be ordered reliably.
        """
        doc = {
            "timestamp": datetime.utcnow(),
            "event": event,
            "performed_by": performed_by,
            "target": _sanitize_audit_value(target, "target"),
            "details": _sanitize_audit_value(details),
        }

        # Insert directly to the audit collection; callers should handle
        # any exceptions from the database layer if they need retries.
        self.audit_log.insert_one(doc)

    def log_event(self, event, performed_by, details=""):
        """Compatibility wrapper: keep older callsites working by forwarding
        to `audit()` which performs the real insert and sanitization.
        """
        return self.audit(event, performed_by, details=details)


    def get_user(self, username: str):
        """
        Return the full user document including _id.
        """
        return self.users.find_one({"username": username})

    def get_next_sales_order_number(self):
        result = self.counters.find_one_and_update(
            {"_id": "sales_order"},
            {"$inc": {"seq": 1}},
            upsert=True,
            return_document=True
        )
        return result["seq"]

    def get_next_works_order_number(self):
        last = self.works_orders.find_one(sort=[("wo_number", -1)])
        return str(int(last["wo_number"]) + 1) if last else "1"

    def get_next_shop_order_number(self):
        last = self.shop_orders.find_one(sort=[("sho_number", -1)])
        if last and "sho_number" in last:
            return str(int(last["sho_number"]) + 1)
        return "1"

    def now(self):
        from datetime import datetime
        return datetime.utcnow()

    def get_sales_orders_active(self):
        return list(self.sales_orders.find({
            "status": {"$nin": ["finished", "cancelled"]}
        }))

    def get_works_orders_active(self):
        return list(self.works_orders.find({
            "status": {"$nin": ["finished", "cancelled"]}
        }))

    def get_shop_orders_active(self):
        return list(self.shop_orders.find({
            "status": {"$nin": ["finished", "cancelled"]}
        }))

