"""Autogenerated module docstring for access\services\permission_service.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:23.128384Z
"""


from functools import wraps
from PySide6.QtWidgets import QMessageBox

def requires_permission(permission):
    """function requires_permission - TODO: add description.
    Generated: 2026-08-01T21:49:18.373710Z
    """
    def decorator(func):
        @wraps(func)
        """function decorator - TODO: add description.
        Generated: 2026-08-01T21:49:18.373710Z
        """
        def wrapper(self, *args, **kwargs):
            """function wrapper - TODO: add description.
            Generated: 2026-08-01T21:49:18.373710Z
            """
            user = getattr(self, "current_user", None)
            if not user or permission not in user.permissions:
                QMessageBox.warning(self, "Access Denied",
                                    "You do not have permission to access this feature.")
                return
            return func(self, *args, **kwargs)
        return wrapper
    return decorator

def has_permission(user, permission: str) -> bool:
    """function has_permission - TODO: add description.
    Generated: 2026-08-01T21:49:18.373710Z
    """
    if not user:
        return False
    return permission in user.permissions