
"""Autogenerated module docstring for access/ui/pages/sales/add_item_dialog.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:24.092140Z
"""
from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QFormLayout, QLineEdit, QComboBox,
    QDialogButtonBox, QListWidget, QListWidgetItem, QPushButton,
    QHBoxLayout, QCalendarWidget, QInputDialog, QLabel, QDateEdit, QSpinBox
)
from PySide6.QtCore import Qt, QDate, QTimer
from PySide6.QtWidgets import QDoubleSpinBox
from ui.components.logger_utils import log_event




class AddItemDialog(QDialog):
    """
    Dialog for creating a new Sales Order entry.

    Accepts:
        mongo: MongoDB client/connection
        user: current user object (optional, for audit logging)
        parent: parent widget

    Fields:
        - SO Number (manual entry for now)
        - Customer (dropdown populated from suppliers collection)
        - Req Date (calendar selector)
        - Items (manually entered list)
        - Status (text box)
        - Type (dropdown: enquiry / firm)
    """

    def __init__(self, mongo, user=None, parent=None):
        super().__init__(parent)

        self.mongo = mongo
        self.user = user

        self.setWindowTitle("Add Sales Order Item")
        self.setMinimumWidth(450)

        # Fetch customers from MongoDB
        suppliers_collection = self.mongo.suppliers
        customers = [doc.get("name", "") for doc in suppliers_collection.find({})]

        # Main layout
        main_layout = QVBoxLayout(self)

        # Form layout
        form = QFormLayout()

        # SO Number (manual for now)
        self.so_number_edit = QLineEdit()
        self.so_number_edit.setText(str(self.mongo.get_next_sales_order_number()))
        self.so_number_edit.setReadOnly(True)

        form.addRow("SO Number:", self.so_number_edit)

        # Customer dropdown
        self.customer_combo = QComboBox()
        self.customer_combo.addItems(customers)
        form.addRow("Customer:", self.customer_combo)

        # Req Date (calendar selector)
        self.req_date_edit = QDateEdit()
        self.req_date_edit.setCalendarPopup(True)
        self.req_date_edit.setDate(QDate.currentDate())
        form.addRow("Req Date:", self.req_date_edit)


        # Status (fixed workflow list)
        # self.status = "new"

        # Type dropdown
        self.type_combo = QComboBox()
        self.type_combo.addItems(["enquiry", "firm"])
        form.addRow("Type:", self.type_combo)

        main_layout.addLayout(form)

        # -------------------------
        # Items list + inventory search + per-item quantity
        # -------------------------
        items_layout = QVBoxLayout()

        # Current items on the sales order
        self.items_list = QListWidget()
        items_layout.addWidget(QLabel("Order Items:"))
        items_layout.addWidget(self.items_list)

        # Inventory search area
        search_layout = QHBoxLayout()
        self.inventory_search = QLineEdit()
        self.inventory_search.setPlaceholderText("Search inventory...")
        self.inventory_search.textChanged.connect(self._search_inventory)
        search_layout.addWidget(self.inventory_search)

        items_layout.addLayout(search_layout)

        self.inventory_results = QListWidget()
        items_layout.addWidget(self.inventory_results)

        # Per-item quantity and UOM display (placed next to Add button)
        pick_layout = QHBoxLayout()

        self.uom_label = QLabel("")                 # shows selected item's UOM

        self.qty_edit = QDoubleSpinBox()
        self.qty_edit.setFixedWidth(80)
        self.qty_edit.setMinimum(0.0)
        self.qty_edit.setMaximum(999999.0)
        self.qty_edit.setDecimals(3)        # allow decimals
        self.qty_edit.setSingleStep(0.1)    # step size for + / -
        self.qty_edit.setValue(1.0)



        pick_layout.addWidget(QLabel("Qty:"))
        pick_layout.addWidget(self.qty_edit)
        pick_layout.addWidget(QLabel("UOM:"))
        pick_layout.addWidget(self.uom_label)
        pick_layout.addStretch()

        # Add / Remove buttons
        btn_layout = QHBoxLayout()
        self.add_item_btn = QPushButton("Add Selected Item")
        self.remove_item_btn = QPushButton("Remove Selected")
        btn_layout.addWidget(self.add_item_btn)
        btn_layout.addWidget(self.remove_item_btn)

        items_layout.addLayout(pick_layout)
        items_layout.addLayout(btn_layout)

        main_layout.addLayout(items_layout)

        # Connections for the new widgets
        self.inventory_results.currentItemChanged.connect(self._on_inventory_selected)

        # Dialog buttons
        buttons = QDialogButtonBox(
            QDialogButtonBox.Ok | QDialogButtonBox.Cancel,
            Qt.Horizontal,
            self
        )
        main_layout.addWidget(buttons)

        # Connections
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.close)   # <-- FIX: force close on Cancel
        self.add_item_btn.clicked.connect(self._add_selected_inventory_item)
        self.remove_item_btn.clicked.connect(self.remove_item)        
        self.inventory_search.textChanged.connect(self._search_inventory)

        # Ensure dialog behaves correctly with calendar + list widgets
        self.setModal(True)
        self.setWindowFlag(Qt.WindowCloseButtonHint, True)


    # Remove selected item
    def remove_item(self):
        for item in self.items_list.selectedItems():
            data = item.data(Qt.UserRole)

            part_number = data.get("part_number")
            qty = data.get("qty")
            uom = data.get("uom")

            # --- Audit log ---
            self.mongo.log_event(
                "sales_order.item_remove",
                performed_by=getattr(self.user, "username", None),
                details=(
                    f"Removed item {part_number} qty {qty} {uom} "
                    f"from Sales Order {self.so_number_edit.text()}"
                )
            )

            # --- Debug log ---
            log_event(
                "info",
                "Sales order item removed",
                user=getattr(self.user, "username", None),
                so_number=self.so_number_edit.text(),
                part_number=part_number,
                qty=qty,
                uom=uom
            )

            # Remove from list
            self.items_list.takeItem(self.items_list.row(item))


    # Gather all data into a dict
    def get_data(self):
        return {
            "so_number": self.so_number_edit.text().strip(),
            "customer": self.customer_combo.currentText(),
            "req_date": self.req_date_edit.date().toString("yyyy-MM-dd"),
            "status": "new",
            "type": self.type_combo.currentText(),
            "items": [
                {
                    "part_number": self.items_list.item(i).data(Qt.UserRole)["part_number"],
                    "description": self.items_list.item(i).data(Qt.UserRole)["description"],
                    "uom": self.items_list.item(i).data(Qt.UserRole).get("uom", "ea"),
                    "qty": self.items_list.item(i).data(Qt.UserRole)["qty"]
                }
                for i in range(self.items_list.count())
            ],
            "created_by": getattr(self.user, "username", None)
        }

    def _search_inventory(self):
        query = self.inventory_search.text().strip().lower()
        self.inventory_results.clear()

        if not query:
            return

        # Search inventory collection
        results = self.mongo.inventory.find({
            "part_number": {"$regex": query, "$options": "i"}
        })

        for item in results:
            display = f"{item.get('part_number', '')} - {item.get('description', '')}"
            list_item = QListWidgetItem(display)
            list_item.setData(Qt.UserRole, item)  # store full item
            self.inventory_results.addItem(list_item)




    def _add_selected_inventory_item(self):
        # Reentrancy guard
        if getattr(self, "_adding_item", False):
            return
        self._adding_item = True

        try:
            selected = self.inventory_results.currentItem()
            if not selected:
                return

            # Capture data immediately
            item = selected.data(Qt.UserRole)
            part_number = item.get("part_number", "")
            description = item.get("description", "")
            uom = item.get("uom", "ea")

            # Normalize quantity using the cleaned, rounded value from the spinbox
            qty_value = self._clean_qty()
            decimals = self.qty_edit.decimals()

            # Store numeric quantity: int when no decimals, float otherwise
            qty_store = int(qty_value) if decimals == 0 else float(qty_value)
            # Format text for display with fixed decimals when applicable
            qty_text = f"{qty_value:.{decimals}f}" if decimals > 0 else str(qty_store)

            # Basic numeric validation
            if decimals == 0 and qty_store < 1:
                from PySide6.QtWidgets import QMessageBox
                QMessageBox.warning(self, "Invalid quantity", "Please enter a positive integer quantity.")
                return
            if decimals > 0 and qty_store < 0:
                from PySide6.QtWidgets import QMessageBox
                QMessageBox.warning(self, "Invalid quantity", "Please enter a non-negative quantity.")
                return

            display = f"{part_number} - {description} (qty: {qty_text.rstrip('0').rstrip('.')} {uom})"
            list_item = QListWidgetItem(display)
            list_item.setData(Qt.UserRole, {
                "part_number": part_number,
                "description": description,
                "uom": uom,
                "qty": qty_store
            })

            try:
            # Defensive duplicate suppression: check last item (compare numerically)
                if self.items_list.count() > 0:
                    last = self.items_list.item(self.items_list.count() - 1).data(Qt.UserRole)
                    last_qty = last.get("qty") if last else None
                    try:
                        last_qty_num = float(last_qty)
                    except Exception:
                        last_qty_num = last_qty
                    if last and last.get("part_number") == part_number and last_qty_num == float(qty_store):
                        # duplicate detected — ignore
                        return

                self.items_list.addItem(list_item)

                # Clear selection and reset qty/uom so a second activation won't add a second line
                self.inventory_results.clearSelection()
                self.uom_label.setText("")
                self.qty_edit.setValue(1)
            except Exception as e:
                log_event("error", "Failed to create sales order item",
                        user=self.user.username, error=str(e))
                QMessageBox.critical(self, "Error", f"Failed to create item:\n{e}")    

        finally:
            # Release guard after a short delay to avoid immediate re-entrancy
            QTimer.singleShot(150, lambda: setattr(self, "_adding_item", False))

    def _on_inventory_selected(self, current, previous):
        if not current:
            self.uom_label.setText("")
            return

        item = current.data(Qt.UserRole)
        uom = item.get("uom", "ea")
        self.uom_label.setText(uom)

        # Fetch UOM metadata from database
        uom_info = self._get_uom_info(uom)
        qty_type = uom_info.get("quantity_type", "integer")  # default fallback

        if qty_type == "decimal":
            self.qty_edit.setDecimals(3)
            self.qty_edit.setSingleStep(0.1)
            qty_value = self._clean_qty()
            self.qty_edit.setMinimum(0.0)
            self.qty_edit.setValue(qty_value)   # ✔ FIX

        else:
            self.qty_edit.setDecimals(0)
            self.qty_edit.setSingleStep(1.0)
            qty_value = self._clean_qty()
            self.qty_edit.setMinimum(1)
            self.qty_edit.setValue(qty_value)   # ✔ FIX



        self.qty_edit.setFocus()


    def _get_uom_info(self, uom):
        return self.mongo.uom_list.find_one({"uom": uom}) or {}

    def _clean_qty(self):
        decimals = self.qty_edit.decimals()
        value = round(self.qty_edit.value(), decimals)
        return float(f"{value:.{decimals}f}")
