
"""Autogenerated module docstring for access/ui/pages/sales/add_item_dialog.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:24.092140Z
"""
from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QFormLayout, QLineEdit, QComboBox,
    QDialogButtonBox, QListWidget, QPushButton, QHBoxLayout,
    QCalendarWidget, QInputDialog
)
from PySide6.QtCore import Qt, QDate


class AddItemDialog(QDialog):
    """
    Dialog for creating a new Sales Order entry.

    Accepts:
        mongo: MongoDB client/connection
        user: current user object (optional, for audit logging)
        parent: parent widget

    Fields:
        - SO Number (manual entry for now)
        - Customer (dropdown populated from suppliers collection)
        - Req Date (calendar selector)
        - Items (manually entered list)
        - Status (text box)
        - Type (dropdown: enquiry / firm)
    """

    def __init__(self, mongo, user=None, parent=None):
        super().__init__(parent)

        self.mongo = mongo
        self.user = user

        self.setWindowTitle("Add Sales Order Item")
        self.setMinimumWidth(450)

        # Fetch customers from MongoDB
        suppliers_collection = self.mongo.suppliers
        customers = [doc.get("name", "") for doc in suppliers_collection.find({})]

        # Main layout
        main_layout = QVBoxLayout(self)

        # Form layout
        form = QFormLayout()

        # SO Number (manual for now)
        self.so_number_edit = QLineEdit()
        self.so_number_edit.setText(str(self.mongo.get_next_sales_order_number()))
        self.so_number_edit.setReadOnly(True)

        form.addRow("SO Number:", self.so_number_edit)

        # Customer dropdown
        self.customer_combo = QComboBox()
        self.customer_combo.addItems(customers)
        form.addRow("Customer:", self.customer_combo)

        # Req Date (calendar selector)
        self.req_date_calendar = QCalendarWidget()
        self.req_date_calendar.setSelectedDate(QDate.currentDate())
        form.addRow("Req Date:", self.req_date_calendar)

        # Status
        self.status_edit = QLineEdit()
        form.addRow("Status:", self.status_edit)

        # Type dropdown
        self.type_combo = QComboBox()
        self.type_combo.addItems(["enquiry", "firm"])
        form.addRow("Type:", self.type_combo)

        main_layout.addLayout(form)

        # Items list + add/remove controls
        items_layout = QVBoxLayout()
        self.items_list = QListWidget()

        # Add/remove buttons
        btn_layout = QHBoxLayout()
        self.add_item_btn = QPushButton("Add Item")
        self.remove_item_btn = QPushButton("Remove Selected")
        btn_layout.addWidget(self.add_item_btn)
        btn_layout.addWidget(self.remove_item_btn)

        items_layout.addWidget(self.items_list)
        items_layout.addLayout(btn_layout)

        main_layout.addLayout(items_layout)

        # Dialog buttons
        buttons = QDialogButtonBox(
            QDialogButtonBox.Ok | QDialogButtonBox.Cancel,
            Qt.Horizontal,
            self
        )
        main_layout.addWidget(buttons)

        # Connections
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.close)   # <-- FIX: force close on Cancel
        self.add_item_btn.clicked.connect(self.add_item)
        self.remove_item_btn.clicked.connect(self.remove_item)

        # Ensure dialog behaves correctly with calendar + list widgets
        self.setModal(True)
        self.setWindowFlag(Qt.WindowCloseButtonHint, True)


    # Add item to list
    def add_item(self):
        text, ok = QInputDialog.getText(self, "Add Item", "Enter item:")
        if ok and text.strip():
            self.items_list.addItem(text.strip())

    # Remove selected item
    def remove_item(self):
        for item in self.items_list.selectedItems():
            self.items_list.takeItem(self.items_list.row(item))

    # Gather all data into a dict
    def get_data(self):
        return {
            "so_number": self.so_number_edit.text().strip(),
            "customer": self.customer_combo.currentText(),
            "req_date": self.req_date_calendar.selectedDate().toString("yyyy-MM-dd"),
            "status": self.status_edit.text().strip(),
            "type": self.type_combo.currentText(),
            "items": [
                self.items_list.item(i).text()
                for i in range(self.items_list.count())
            ],
            "created_by": getattr(self.user, "username", None)
        }
