"""Autogenerated module docstring for access/ui/pages/sales/sales_order_list_page.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:24.092140Z
"""


from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLineEdit,
    QLabel, QComboBox, QTableView, QTableWidgetItem, QMessageBox
)
from PySide6.QtCore import Qt

from ui.components.logger_utils import log_event
from bson import ObjectId
from ui.pages.sales.add_item_dialog import AddItemDialog
from PySide6.QtGui import QStandardItemModel, QStandardItem
from ui.components.logger_utils import log_event
from ui.pages.sales.edit_sales_order_dialog import EditSalesOrderDialog



class SalesOrderListPage(QWidget):
    def __init__(self, user, mongo, parent=None):
        super().__init__(parent)

        self.user = user
        self.mongo = mongo
        self.app = parent

        log_event("info", "SalesOrderListPage initialized", user=user.username)
        
        self._build_ui()
        self._load_sales_orders()

        self.btn_add.clicked.connect(self._open_add_dialog)
        self.btn_delete.clicked.connect(self._disable_selected_item)
        self.btn_edit.clicked.connect(self._open_edit_dialog)



        # self._load_data() 

    # ---------------------------------------------------------
    # Build UI
    # ---------------------------------------------------------
    def _build_ui(self):
        layout = QVBoxLayout(self)

        # -------------------------
        # Toolbar (Add / Edit / Delete)
        # -------------------------
        toolbar = QHBoxLayout()

        self.btn_add = QPushButton("Add Sales Order")
        self.btn_edit = QPushButton("Edit Sales Order")
        self.btn_delete = QPushButton("Disable Sales Order")
 


        # Permission-aware buttons
        self.btn_add.setEnabled("sales.create" in self.user.permissions or "*" in self.user.permissions)
        self.btn_edit.setEnabled("sales.edit" in self.user.permissions or "*" in self.user.permissions)
        self.btn_delete.setEnabled("sales.edit" in self.user.permissions or "*" in self.user.permissions)


        toolbar.addWidget(self.btn_add)
        toolbar.addWidget(self.btn_edit)
        toolbar.addWidget(self.btn_delete)
        toolbar.addStretch()

        layout.addLayout(toolbar)

        # -------------------------
        # Search + Filters
        # -------------------------
        filter_bar = QHBoxLayout()

        self.search_box = QLineEdit()
        self.search_box.setPlaceholderText("Search Sales Orders...")
        self.search_box.textChanged.connect(self._apply_filters)

        # -------------------------
        # Customer Filter (dynamic)
        # -------------------------

        # Fetch unique customers from MongoDB
        orders = list(self.mongo.sales_orders.find({}))
        customers = sorted({order.get("customer", "") for order in orders if order.get("customer")})

        self.customer_filter = QComboBox()
        self.customer_filter.addItem("All Customers")
        self.customer_filter.addItems(customers)
        self.customer_filter.currentIndexChanged.connect(self._apply_filters)


        self.status_filter = QComboBox()
        self.status_filter.addItems(["All Status","new", "released", "held", "cancelled", "in-work", "finished"])
        self.status_filter.currentIndexChanged.connect(self._apply_filters)

        self.firm_enquiry_filter = QComboBox()
        self.firm_enquiry_filter.addItems(["All", "Firm", "Enquiry"])
        self.firm_enquiry_filter.currentIndexChanged.connect(self._apply_filters)

        filter_bar.addWidget(QLabel("Search:"))
        filter_bar.addWidget(self.search_box)
        filter_bar.addWidget(QLabel("Customer:"))
        filter_bar.addWidget(self.customer_filter)
        filter_bar.addWidget(QLabel("Status:"))
        filter_bar.addWidget(self.status_filter)
        filter_bar.addWidget(QLabel("Firm/Enquiry:"))
        filter_bar.addWidget(self.firm_enquiry_filter)
        filter_bar.addStretch()

        layout.addLayout(filter_bar)

        # -------------------------
        # Table
        # -------------------------
        self.table = QTableView()
        self.table.setSortingEnabled(True)

        # Proxy model for search + filters
        from ui.models.sales_filter_proxy import SalesFilterProxyModel 
        self.proxy = SalesFilterProxyModel()

        self.proxy.setFilterCaseSensitivity(Qt.CaseInsensitive)
        self.proxy.setFilterKeyColumn(-1)  # search all columns

        self.table.setModel(self.proxy)

        layout.addWidget(self.table)


    # ---------------------------------------------------------
    # Apply search + filters
    # ---------------------------------------------------------
    
    def _apply_filters(self):
        self.proxy.set_filters(
            self.search_box.text().strip(),
            self.customer_filter.currentText(),
            self.status_filter.currentText(),
            self.firm_enquiry_filter.currentText().lower()
        )


    def _on_selection_changed(self, selected, deselected):
        """Update UI state when the table selection changes."""
        try:
            has_selection = len(self.table.selectionModel().selectedRows()) > 0
        except Exception:
            has_selection = False

        # Enable/disable edit/delete buttons based on selection and permissions
        self.btn_edit.setEnabled(has_selection and ("sales.edit" in self.user.permissions or "*" in self.user.permissions))
        self.btn_delete.setEnabled(has_selection and ("sales.edit" in self.user.permissions or "*" in self.user.permissions))


    def _disable_selected_item(self):
        selection = self.table.selectionModel().selectedRows()
        if not selection:
            self.window().show_error("Please select a sales order first.")
            return

        index = selection[0]
        model = self.table.model()

        so_number = model.index(index.row(), 0).data()
        if not so_number:
            self.window().show_error("Could not determine sales order number.")
            return

        confirm = QMessageBox.question(
            self,
            "Disable Sales Order",
            f"Are you sure you want to disable Sales Order '{so_number}'?",
            QMessageBox.Yes | QMessageBox.No
        )

        if confirm != QMessageBox.Yes:
            return

        self.mongo.sales_orders.update_one(
            {"so_number": so_number},
            {"$set": {"status": "Disabled"}}
        )

        self.mongo.log_event(
            "sales_order.disable",
            performed_by=self.user.username,
            details=f"Disabled Sales Order {so_number}"
        )

        log_event("info", "Sales order disabled",
                user=self.user.username, so_number=so_number)

        self._load_sales_orders()



    def _open_add_dialog(self):
        dlg = AddItemDialog(self.mongo, self.user, self)

        if dlg.exec():
            data = dlg.get_data()

            # Insert into MongoDB
            self.mongo.sales_orders.insert_one(data)

            self.mongo.log_event(
                "sales_order.create",
                performed_by=getattr(self.user, "username", None),
                details=f"Created Sales Order {data['so_number']} for {data['customer']}"
            )

            log_event(
                "info",
                "Sales order created",
                user=getattr(self.user, "username", None),
                so_number=data["so_number"],
                customer=data["customer"],
                item_count=len(data["items"])
            )

            # Refresh the table/list
            self._load_sales_orders()

            # Optional: audit log
            self.mongo.audit_log.insert_one({
                "event": "sales_order.create",
                "performed_by": getattr(self.user, "username", None),
                "details": data
            })



    def _load_sales_orders(self):
        # Fetch all orders from MongoDB
        orders = list(self.mongo.sales_orders.find({}))

        # Create a model with 5 columns
        model = QStandardItemModel(len(orders), 5)
        model.setHorizontalHeaderLabels([
            "SO Number",
            "Customer",
            "Req Date",
            "Status",
            "Type"
        ])

        # Populate the model
        for row, order in enumerate(orders):
            model.setItem(row, 0, QStandardItem(order.get("so_number", "")))
            model.setItem(row, 1, QStandardItem(order.get("customer", "")))
            model.setItem(row, 2, QStandardItem(order.get("req_date", "")))
            model.setItem(row, 3, QStandardItem(order.get("status", "")))
            model.setItem(row, 4, QStandardItem(order.get("type", "")))

        # ⭐ Attach model to proxy
        self.proxy.setSourceModel(model)

        # ⭐ Ensure table uses the proxy (not the raw model)
        self.table.setModel(self.proxy)

        # Resize columns
        self.table.resizeColumnsToContents()

        # ⭐ Reconnect selectionChanged (new model = new selectionModel)
        self.table.selectionModel().selectionChanged.connect(self._on_selection_changed)






    def _open_receive_stock_dialog(self):
        selection = self.table.selectionModel().selectedRows()
        if not selection:
            self.window().show_error("Please select an item first.")
            return

        index = selection[0]
        source_index = self.proxy.mapToSource(index)
        model = self.proxy.sourceModel()

        item_id = model.index(source_index.row(), 0).data(Qt.UserRole)
        item = self.mongo.inventory.find_one({"_id": item_id})

        from ui.pages.inventory.receive_stock_dialog import ReceiveStockDialog
        dlg = ReceiveStockDialog(self.mongo, self.user, item, self)
        if dlg.exec():
            self.window().show_info("Stock received successfully.")



    def _open_batch_list(self):
        import ui.pages.inventory.batch_list_page as blp
        import inspect


        import ui.pages.inventory.batch_list_page as blp



        try:
            from ui.pages.inventory.batch_list_page import BatchListPage

        except Exception as e:

            return



        selection = self.table.selectionModel().selectedRows()


        if not selection:
            self.window().show_error("Please select an item first.")
            return

        index = selection[0]


        source_index = self.proxy.mapToSource(index)


        model = self.proxy.sourceModel()


        try:
            item_id = model.index(source_index.row(), 0).data(Qt.UserRole)

        except Exception as e:

            self.window().show_error(f"Failed to get item ID: {e}")
            return

        # a THIS MUST BE HERE a otherwise 'item' does not exist
        item = self.mongo.inventory.find_one({"_id": ObjectId(item_id)})


        if not item:

            self.window().show_error("Item not found in database.")
            return

        # Test import
        try:
            from ui.pages.inventory.batch_list_page import BatchListPage

        except Exception as e:

            self.window().show_error(f"Import failed: {e}")
            return


        self.batch_window = BatchListPage(self.mongo, item, user=self.user)

        self.batch_window.show()

    def _open_edit_dialog(self):
        index = self.table.currentIndex()

        if not index.isValid():
            QMessageBox.warning(
                self,
                "No Selection",
                "Please select a sales order to edit."
            )
            return

        model = self.table.model()
        so_number = model.data(model.index(index.row(), 0))

        if not so_number:
            QMessageBox.critical(self, "Error", "Could not determine Sales Order number.")
            return

        # Fetch full sales order document
        so = self.mongo.sales_orders.find_one({"so_number": so_number})
        if not so:
            QMessageBox.critical(self, "Error", f"Sales Order {so_number} not found.")
            return

        # ⭐ BLOCK EDITING IF DISABLED ⭐
        if so.get("status", "").lower() == "disabled":
            QMessageBox.warning(
                self,
                "Sales Order Disabled",
                f"Sales Order {so_number} is disabled and cannot be edited."
            )
            return

        # Open edit dialog
        dlg = EditSalesOrderDialog(self.mongo, self.user, so, self)
        if dlg.exec():
            updated_data = dlg.get_data()
            ...


    def _open_move_dialog(self):
        selection = self.table.selectionModel().selectedRows()
        if not selection:
            self.window().show_error("Please select an item first.")
            return

        index = selection[0]
        source_index = self.proxy.mapToSource(index)
        model = self.proxy.sourceModel()

        item_id = model.index(source_index.row(), 0).data(Qt.UserRole)
        item = self.mongo.inventory.find_one({"_id": item_id})

        from ui.pages.inventory.stock_movement_dialog import StockMovementDialog
        dlg = StockMovementDialog(self.mongo, self.user, item, self)

        if dlg.exec():
            self.window().show_info("Stock moved successfully.")

    def _open_edit_dialog(self):
        index = self.table.currentIndex()

        # No row selected
        if not index.isValid():
            QMessageBox.warning(
                self,
                "No Selection",
                "Please select a sales order to edit."
            )
            return


        # Extract the SO number from the model
        model = self.table.model()
        so_number = model.data(model.index(index.row(), 0))  # assuming column 0 = SO number

        if not so_number:
            QMessageBox.critical(self, "Error", "Could not determine Sales Order number.")
            return

        # Fetch full sales order document
        so = self.mongo.sales_orders.find_one({"so_number": so_number})
        if not so:
            QMessageBox.critical(self, "Error", f"Sales Order {so_number} not found.")
            return

        # Open edit dialog
        dlg = EditSalesOrderDialog(self.mongo, self.user, so, self)
        if dlg.exec():
            updated_data = dlg.get_data()

            try:
                # Update in MongoDB
                self.mongo.sales_orders.update_one(
                    {"so_number": so_number},
                    {"$set": updated_data}
                )

                # Audit log
                self.mongo.log_event(
                    "sales_order.update",
                    performed_by=getattr(self.user, "username", None),
                    details=f"Updated Sales Order {so_number}"
                )

                # Debug log
                log_event(
                    "info",
                    "Sales order updated",
                    user=getattr(self.user, "username", None),
                    so_number=so_number,
                    item_count=len(updated_data.get("items", [])),
                    status=updated_data.get("status")
                )

                # Reload table
                self._load_sales_orders()

            except Exception as e:
                log_event(
                    "error",
                    "Failed to update sales order",
                    user=getattr(self.user, "username", None),
                    so_number=so_number,
                    error=str(e)
                )
                QMessageBox.critical(self, "Error", f"Failed to update Sales Order:\n{e}")

    def _on_selection_changed(self, selected, deselected):
        index = self.table.currentIndex()

        if not index.isValid():
            self.btn_edit.setEnabled(False)
            return

        proxy = self.table.model()          # this is SalesFilterProxyModel
        source_index = proxy.mapToSource(index)
        source_model = proxy.sourceModel()

        status = source_model.data(source_model.index(source_index.row(), 3))

        if not status:
            self.btn_edit.setEnabled(False)
            return

        if status.lower() == "disabled":
            self.btn_edit.setEnabled(False)
        else:
            self.btn_edit.setEnabled(True)