"""Autogenerated module docstring for access/ui/components/dialogs.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:23.223059Z
"""


from PySide6.QtWidgets import QMessageBox

def show_access_denied(parent=None):
    QMessageBox.warning(parent, "Access Denied",
                        "You do not have permission to access this feature.")
