"""Autogenerated module docstring for access/main.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:22.921909Z
"""


from PySide6.QtWidgets import QApplication
from ui.pages.login_page import LoginWindow

app = QApplication([])
window = LoginWindow()
window.show()
app.exec()