"""Autogenerated module docstring for access/page_registry.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:22.985644Z
"""


PAGE_REGISTRY = {
    "User Manager": {"default_permission": "none"},
    "Permissions": {"default_permission": "none"},
    "System Info": {"default_permission": "ro"},
    "Logs": {"default_permission": "ro"},
}