"""Autogenerated module docstring for access/ui/models/sales_filter_proxy.py

Description: TODO - add a meaningful module description.
Generated: 2026-08-01T21:47:23.410402Z
"""


from PySide6.QtCore import QSortFilterProxyModel, Qt

class SalesFilterProxyModel(QSortFilterProxyModel):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.search_text = ""
        self.type_filter = "All Types"
        self.status_filter = "All Status"
        self.firm_enquiry_filter = "All"

    def set_filters(self, search_text, type_filter, status_filter, firm_enquiry_filter):
        self.search_text = (search_text or "").lower()
        self.type_filter = type_filter
        self.status_filter = status_filter
        self.firm_enquiry_filter = firm_enquiry_filter
        self.invalidateFilter()

    def filterAcceptsRow(self, row, parent):
        model = self.sourceModel()
        if model is None:
            return True

        # Extract row data
        row_data = [
            model.index(row, col).data()
            for col in range(model.columnCount())
        ]

        # Search filter
        if self.search_text:
            if not any(self.search_text in str(cell).lower() for cell in row_data):
                return False

        # Type filter
        if self.type_filter and self.type_filter != "All Types":
            # Apply type filter across all columns for resilience
            if not any(str(cell) == self.type_filter for cell in row_data):
                return False

        # Status filter
        if self.status_filter and self.status_filter != "All Status":
            if not any(str(cell) == self.status_filter for cell in row_data):
                return False

        # Firm/Enquiry filter
        if self.firm_enquiry_filter.lower() != "all":
            if not any(str(cell).lower() == self.firm_enquiry_filter.lower() for cell in row_data):
                return False


        return True